name: .github/workflows/security-scan.yml

# Run this pipeline automatically whenever code is pushed to the repository
on: [push]

jobs:
  scan-code:
    runs-on: ubuntu-latest # Use a temporary Linux computer
    steps:
      - name: Step 1 - Copy project files
        uses: actions/checkout@v4

      - name: Step 2 - Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Step 3 - Install and Run Semgrep SAST
        run: |
          pip install semgrep
          semgrep scan --config=auto --error
